[theme]

# Primary accent for interactive elements
primaryColor = '#9FB1BCFF'

# Background color for the main content area
backgroundColor = '#2E5266FF'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#6E8898FF'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"